name: Deploy to SSH VPS

on:
  push:
    branches:
      - new

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Connect to remote server via SSH to start the bot using PM2
      - name: Start API with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/trident/github/turing-api-new
            npm run git
            npm i
            rm -r dist
            npm run build
            pm2 reload TuringAPINew
